# Generated by Django 3.2.4 on 2021-06-29 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_amount_ingredients_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Номер шага')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
                ('dis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipe.dish', verbose_name='Блюдо')),
            ],
            options={
                'verbose_name': 'Этапы',
                'verbose_name_plural': 'Этапы',
                'ordering': ['id', 'dis', 'name'],
            },
        ),
    ]
