# Generated by Django 3.2.4 on 2021-07-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_advice_instruments_serving'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='steps',
            field=models.TextField(blank=True, verbose_name='Шаги приготовления'),
        ),
        migrations.DeleteModel(
            name='Step',
        ),
    ]
